export const occupation = {
    "Occupation" : [
        "Accountant",
        "Acting Professional",
        "Actor",
        "Administration Professional",
        "Advertising Professional",
        "Air Hostess",
        "Analyst",
        "Architect",
        "Artisan",
        "Artist",
        "Audiologist",
        "Auditor",
        "Banker",
        "Beautician",
        "Biologist / Botanist",
        "Business",
        "Carpenter",
        "Chartered Accountant",
        "Civil Engineer",
        "Clerical Official",
        "Commercial Pilot",
        "Company Secretary",
        "Computer Professional",
        "Consultant",
        "Content Writer",
        "Contractor",
        "Cook",
        "Cost Accountant",
        "Creative Person",
        "Customer Support Professional",
        "Defense Employee",
        "Dentist",
        "Designer",
        "Doctor",
        "Driver",
        "Economist",
        "Electrician",
        "Engineer",
        "Engineer (Mechanical)",
        "Engineer (Project)",
        "Engineer Non - IT",
        "Entertainment Professional",
        "Event Manager",
        "Executive",
        "Factory Worker",
        "Farmer",
        "Fashion Designer",
        "Finance Professional",
        "Flight Attendant",
        "Freelance - Professional",
        "Government Employee",
        "Gym Trainer",
        "Health Care Professional",
        "Home Maker",
        "Hotel & Restaurant Professional",
        "Housekeeper",
        "Human Resources Professional",
        "Interior Designer",
        "Investment Professional",
        "IT / Telecom Professional",
        "Janitor",
        "Journalist",
        "Lab Technician",
        "Lawyer",
        "Lecturer",
        "Legal Professional",
        "Maid",
        "Manager",
        "Marketing Professional",
        "Mechanic",
        "Media Professional",
        "Medical Professional",
        "Medical Transcriptionist",
        "Merchant Naval Officer",
        "Military",
        "Musician",
        "Non-Mainstream Professional",
        "Not Working",
        "Nurse",
        "Occupational Therapist",
        "Optician",
        "Pharmacist",
        "Physician Assistant",
        "Physicist",
        "Physiotherapist",
        "Pilot",
        "Police",
        "Politician",
        "Production Professional",
        "Professor",
        "Programmer",
        "Psychologist",
        "Public Relations Professional",
        "Real Estate Professional",
        "Research Scholar",
        "Retail Professional",
        "Retired Person",
        "Teacher",
        "Others",
    ]
}